/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { PlanillaData } from "./types";

export const initialEmptyData: PlanillaData = {
  docenteNombre: "",
  cargo: "Maestra/o de Grado",
  modulo: "",
  turno: "Mañana",
  frenteDia: "",
  frenteMes: "",
  frenteAnio: "2026",
  dorsoDia: "",
  dorsoMes: "",
  dorsoAnio: "2026",
  dorsoMesDe: "",
  estudiantes: [],
  asistenciaClasesDadas: "",
  asistenciaAsistencias: "",
  asistenciaLicencias: "",
  asistenciaDiasHabiles: "",
  asistenciaObservaciones: "",
  dorsoObservaciones: "",
};

export const examplePlanillaData: PlanillaData = {
  docenteNombre: "Andrea Gómez",
  cargo: "Maestra/o de Grado",
  modulo: "Módulo I",
  turno: "Mañana",
  frenteDia: "15",
  frenteMes: "07",
  frenteAnio: "2022",
  dorsoDia: "01",
  dorsoMes: "08",
  dorsoAnio: "2022",
  dorsoMesDe: "Agosto",
  estudiantes: [
    {
      id: "1",
      orden: 1,
      nomina: "Susanita Giménez",
      grado: "3°",
      edad: "8",
      nac: "arg.",
      diagnostico: "Broncoespasmo.",
      domicilio: "Av. Gaona 803 – 1° A.",
      telefono: "11-8888-2002",
      incluirFrente: true,
      incluirDorso: true,
      frenteAus: "1",
      frentePres: "3",
      frenteHorario: "Martes y jueves 08:00 a 10:00 hs.",
      frenteCalif: "",
      frenteObservaciones: "Fecha de ingreso del/la alumno/a.",
      dorsoDias: "Martes y jueves",
      dorsoHoras: "08:00 a 10:00 hs.",
      dorsoTotalHoras: "8",
    },
    {
      id: "2",
      orden: 2,
      nomina: "Nicolás Fernández",
      grado: "2 años.",
      edad: "2",
      nac: "arg.",
      diagnostico: "Hipotonía.",
      domicilio: "Otamendi 1245 – 9° B.",
      telefono: "0234-99-6098",
      incluirFrente: true,
      incluirDorso: true,
      frenteAus: "-",
      frentePres: "4",
      frenteHorario: "Martes y jueves 10:00 a 12:15 hs.",
      frenteCalif: "",
      frenteObservaciones: "Si el alumno egresó, se coloca la fecha de egreso, por ej: 15/07/2022.",
      dorsoDias: "Martes y jueves",
      dorsoHoras: "10:00 a 12:15 hs.",
      dorsoTotalHoras: "9",
    },
    {
      id: "3",
      orden: 3,
      nomina: "María Ressa",
      grado: "1°",
      edad: "6",
      nac: "fil.",
      diagnostico: "Agarofobia.",
      domicilio: "Mansilla 4239.",
      telefono: "",
      incluirFrente: true,
      incluirDorso: false,
      frenteAus: "1",
      frentePres: "3",
      frenteHorario: "Lunes y miércoles 10:00 a 12:00 hs.",
      frenteCalif: "",
      frenteObservaciones: "",
      dorsoDias: "",
      dorsoHoras: "",
      dorsoTotalHoras: "",
    },
    {
      id: "4",
      orden: 4,
      nomina: "Hospital Rivadavia",
      grado: "",
      edad: "",
      nac: "",
      diagnostico: "Patologías varias.",
      domicilio: "Av. Las Heras 2670.",
      telefono: "",
      incluirFrente: true,
      incluirDorso: true,
      frenteAus: "-",
      frentePres: "8",
      frenteHorario: "Lunes y miércoles 08:00 a 10:00 hs.",
      frenteCalif: "",
      frenteObservaciones: "",
      dorsoDias: "Lunes y miércoles",
      dorsoHoras: "08:00 a 12:15 hs.",
      dorsoTotalHoras: "16",
    },
    {
      id: "5",
      orden: 5,
      nomina: "Marianito Andújar",
      grado: "7°",
      edad: "12",
      nac: "col.",
      diagnostico: "Esguince de tobillo.",
      domicilio: "Serrano 2633 – casa.",
      telefono: "0221–98-7777",
      incluirFrente: true,
      incluirDorso: true,
      frenteAus: "1",
      frentePres: "1",
      frenteHorario: "Viernes 09:00 a 10:30 hs.",
      frenteCalif: "",
      frenteObservaciones: "",
      dorsoDias: "Viernes",
      dorsoHoras: "09:00 a 10:30 hs.",
      dorsoTotalHoras: "3",
    },
    {
      id: "6",
      orden: 6,
      nomina: "Max Verstappen",
      grado: "Sala de 4 años.",
      edad: "4",
      nac: "hol.",
      diagnostico: "Fractura de muñeca.",
      domicilio: "Virasoro 3002.",
      telefono: "11-9988-2022",
      incluirFrente: true,
      incluirDorso: true,
      frenteAus: "-",
      frentePres: "1",
      frenteHorario: "Viernes 10:30 a 12:00 hs.",
      frenteCalif: "",
      frenteObservaciones: "",
      dorsoDias: "Viernes.",
      dorsoHoras: "10:30 a 12:00 hs",
      dorsoTotalHoras: "3",
    }
  ],
  asistenciaClasesDadas: "20.",
  asistenciaAsistencias: "7 días",
  asistenciaLicencias: "receso escolar de invierno y licencias indicadas en observaciones si corresponde.",
  asistenciaDiasHabiles: "11 días.",
  asistenciaObservaciones: "06/07 reunión de personal (en el mes de julio los docentes tuvieron reunión en diferentes fechas con sus vicedirectores - Graciela: 06/07 - Alejandra: 07/07, Marcela: 08/07).\n18/07 al 29/07: receso escolar de invierno.",
  dorsoObservaciones: "En Cargo, colocar según corresponda: Maestra/o de Educación Musical / Maestro/a de Educación Plástica / Maestro/a de Educación Artesanal y Técnica / Maestra/o de Grado / Maestra de Atención Temprana / Maestra de Sección. Horario completo según DDJJ.",
};
